/**
 * Layout Component
 *
 * Main layout orchestrator for the application.
 * This component is generated by `frontx scaffold layout`.
 * Uses local shadcn/ui components.
 */

import React, { useEffect } from 'react';
import { fetchCurrentUser } from '@/app/actions/bootstrapActions';
import { Header } from './Header';
import { Menu } from './Menu';
import { Sidebar } from './Sidebar';
import { Screen } from './Screen';
import { Popup } from './Popup';
import { Overlay } from './Overlay';

export interface LayoutProps {
  children?: React.ReactNode;
}

export const Layout: React.FC<LayoutProps> = ({ children }) => {
  useEffect(() => {
    // Bootstrap application on mount - fetch current user
    fetchCurrentUser();
  }, []);

  return (
    <div className="flex flex-col h-full w-full overflow-hidden">
      {/* Top row: Menu + Header + Content + Sidebar */}
      <div className="flex flex-1 overflow-hidden">
        {/* Menu - full height on left */}
        <Menu />

        {/* Right side: Header + Content */}
        <div className="flex flex-col flex-1 overflow-hidden">
          {/* Header */}
          <Header />

          {/* Main content area */}
          <div className="flex flex-1 overflow-hidden">
            {/* Main content */}
            <Screen>{children}</Screen>

            {/* Sidebar */}
            <Sidebar />
          </div>
        </div>
      </div>

      {/*
        No <Footer /> here on purpose: it frames the children it is given and
        this layout has none for it, so mounting one would lay an empty
        full-width band under every screen. A project with something to show
        there renders `Footer` itself, with that content as its children.
      */}

      {/* Popups */}
      <Popup />

      {/* Overlay */}
      <Overlay />
    </div>
  );
};

Layout.displayName = 'Layout';
