/**
 * Overlay Component
 *
 * Full-screen overlay for modals and loading states.
 * Generated by `frontx scaffold layout`.
 */

import React from 'react';
import { useAppSelector, type OverlayState } from '@gears-frontx/react';

export interface OverlayProps {
  children?: React.ReactNode;
}

export const Overlay: React.FC<OverlayProps> = ({ children }) => {
  const overlayState = useAppSelector((state) => state['layout/overlay'] as OverlayState | undefined);
  const visible = overlayState?.visible ?? false;

  if (!visible) {
    return null;
  }

  return (
    <div className="fixed inset-0 z-50 bg-[color-mix(in_oklab,var(--background)_80%,transparent)] backdrop-blur-sm flex items-center justify-center">
      {children}
    </div>
  );
};

Overlay.displayName = 'Overlay';
