/**
 * Popup Component
 *
 * Modal dialog container.
 * Generated by `frontx scaffold layout`.
 */

import React from 'react';
import { useAppSelector, type PopupSliceState } from '@gears-frontx/react';

export interface PopupProps {
  children?: React.ReactNode;
}

export const Popup: React.FC<PopupProps> = ({ children }) => {
  const popupState = useAppSelector((state) => state['layout/popup'] as PopupSliceState | undefined);
  const stack = popupState?.stack ?? [];

  if (stack.length === 0) {
    return null;
  }

  // Render the top popup from the stack
  const topPopup = stack[stack.length - 1];

  return (
    <div className="fixed inset-0 z-[1000] flex items-center justify-center">
      {/* Backdrop */}
      <div className="absolute inset-0 bg-[color-mix(in_oklab,var(--background)_80%,transparent)] backdrop-blur-sm" />

      {/* Dialog - z-index is calculated as 1000 + stack depth * 10 */}
      <div className="relative z-[1001] w-full max-w-lg rounded-lg border border-border bg-background p-6 shadow-lg">
        {topPopup.title && (
          <div className="mb-4">
            <h2 className="text-lg font-semibold">{topPopup.title}</h2>
          </div>
        )}
        {children}
      </div>
    </div>
  );
};

Popup.displayName = 'Popup';
