/**
 * Sidebar Component
 *
 * Right-side panel for contextual content.
 * Generated by `frontx scaffold layout`.
 */

import React from 'react';
import { useAppSelector, type SidebarState } from '@gears-frontx/react';

export interface SidebarProps {
  children?: React.ReactNode;
}

export const Sidebar: React.FC<SidebarProps> = ({ children }) => {
  const sidebarState = useAppSelector((state) => state['layout/sidebar'] as SidebarState | undefined);

  const visible = sidebarState?.visible ?? false;
  const collapsed = sidebarState?.collapsed ?? true;

  if (!visible) {
    return null;
  }

  return (
    <aside className={`border-l border-border bg-background transition-all duration-200 ${collapsed ? 'w-0' : 'w-80'}`}>
      <div className="h-full overflow-y-auto p-4">
        {children}
      </div>
    </aside>
  );
};

Sidebar.displayName = 'Sidebar';
